In [2]:
import numpy as np
dataset_filename='C:/Users/Administrator/Desktop/p0.txt'   #only the code=utf-8 is ok
#X=np.loadtxt(dataset_filename)           some problem with this code: UnicodeDecodeError 
X=np.genfromtxt(dataset_filename)           

In [3]:
print(X[:5])           #result show that the first number is missing, it's the problem resulted into loadtxt failed? 


[[ nan   1.   0.   1.   0.]
 [  0.   0.   1.   0.   0.]
 [  1.   0.   1.   0.   0.]
 [  1.   0.   1.   1.   1.]
 [  0.   1.   1.   0.   1.]]


In [4]:
num_apple_purchase=0
for sample in X:
    if sample[3]==1:
        num_apple_purchase+=1
print('{0} people bought apples'.format(num_apple_purchase))
features=['pear','milk','banana','apple','bread']
n_features=len(features)

248 people bought apples


In [5]:
from collections import defaultdict
valid_rules=defaultdict(int)
invalid_rules=defaultdict(int)
num_occurances=defaultdict(int)

for sample in X:
    for premise in range(5):
        if sample[premise]==0:
            continue
        num_occurances[premise]+=1
        for conclusion in range(n_features):
            if premise==conclusion:
                continue
            if sample[conclusion]==1:
                valid_rules[(premise,conclusion)]+=1
            else:
                invalid_rules[(premise,conclusion)]+=1
support=valid_rules
confidence=defaultdict(float)
for premise,conclusion in valid_rules.keys():
    rule=(premise,conclusion)
    confidence[rule]=valid_rules[rule]/num_occurances[premise]

def print_rule(premise,conclusion,support,confidence,features):
    premise_name=features[premise]
    conclusion_name=features[conclusion]
    print('rule: if a pearson buys {0} they will buy {1}'.format(premise_name,conclusion_name))
    print('-support:{0}'.format(support[(premise,conclusion)]))
    print('-confidence:{0:.3f}'.format(confidence[(premise,conclusion)]))

In [6]:
premise=1
conclusion=3
print_rule(premise,conclusion,support,confidence,features)

rule: if a pearson buys milk they will buy apple
-support:125
-confidence:0.502


In [21]:
print(valid_rules)
print(invalid_rules)
print(num_occurances)

defaultdict(<class 'int'>, {(0, 1): 122, (0, 3): 122, (1, 3): 125, (3, 1): 125, (0, 2): 125, (2, 0): 125, (0, 4): 130, (2, 3): 127, (2, 4): 126, (3, 0): 121, (3, 2): 127, (3, 4): 130, (4, 0): 130, (4, 2): 126, (4, 3): 130, (1, 2): 110, (1, 4): 135, (2, 1): 110, (4, 1): 135, (1, 0): 121})
defaultdict(<class 'int'>, {(0, 2): 126, (0, 4): 121, (1, 0): 128, (1, 2): 139, (1, 4): 114, (3, 0): 127, (3, 2): 121, (3, 4): 118, (2, 0): 127, (2, 1): 142, (2, 3): 125, (2, 4): 126, (0, 1): 129, (0, 3): 129, (3, 1): 123, (4, 1): 117, (1, 3): 124, (4, 0): 122, (4, 3): 122, (4, 2): 126})
defaultdict(<class 'int'>, {0: 251, 1: 249, 3: 248, 2: 252, 4: 252})


In [8]:
from operator import itemgetter
sorted_support=sorted(support.items(),key=itemgetter(1),reverse=True)
for index in range(5):
    print('rule #{0}'.format(index+1))
    premise,conclusion=sorted_support[index][0]
    print_rule(premise,conclusion,support,confidence,features)

rule #1
rule: if a pearson buys milk they will buy bread
-support:135
-confidence:0.542
rule #2
rule: if a pearson buys bread they will buy milk
-support:135
-confidence:0.536
rule #3
rule: if a pearson buys pear they will buy bread
-support:130
-confidence:0.518
rule #4
rule: if a pearson buys apple they will buy bread
-support:130
-confidence:0.524
rule #5
rule: if a pearson buys bread they will buy pear
-support:130
-confidence:0.516


In [9]:
sorted_confidence=sorted(confidence.items(),key=itemgetter(1),reverse=True)
for index in range(5):
    print('rule #{0}'.format(index+1))
    premise,conclusion=sorted_confidence[index][0]
    print_rule(premise,conclusion,support,confidence,features)

rule #1
rule: if a pearson buys milk they will buy bread
-support:135
-confidence:0.542
rule #2
rule: if a pearson buys bread they will buy milk
-support:135
-confidence:0.536
rule #3
rule: if a pearson buys apple they will buy bread
-support:130
-confidence:0.524
rule #4
rule: if a pearson buys pear they will buy bread
-support:130
-confidence:0.518
rule #5
rule: if a pearson buys bread they will buy pear
-support:130
-confidence:0.516


In [28]:
filename='C:/Users/Administrator/Desktop/p1.txt'   #only the code=utf-8 is ok
#X=np.loadtxt(dataset_filename)           some problem with this code: UnicodeDecodeError 
Y=np.genfromtxt(filename) 

In [35]:
f=open('C:/Users/Administrator/Desktop/p.txt',encoding='utf-8')
print(f.read())

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte